apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-deployment
  annotations:
    generate: "norm"
    generate.gpu.request: "d"
    generate.resource.request.loc: "1"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              nvidia.com/gpu: "0"
              memory: "64Mi"
              cpu: "250m"
            limits:
              nvidia.com/gpu: "0"
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc